export const PINCH_CONFIG = Object.freeze({
  protocol: 'fixedgap-pastillero-assisted-pinch-v2',
  algorithm: '1.0.0',
  model: 'hand_landmarker/float16/1',
  modelSha256: 'fbc2a30080c3c557093b5ddfc334698132eb341044ccee322ccf8bcf3607cde1',
  tasksVersion: '0.10.35',
  targetRepetitions: 17,
  sceneFps: 30,
  transferMs: 650,
  countdownSeconds: 3,
  maxTrialMs: 90000,
  maxSamples: 12000,
  closeRatio: 0.23,
  openRatio: 0.48,
  minExcursion: 0.20,
  closeMs: 100,
  openMs: 140,
  releaseMs: 140,
  stableMs: 650,
  maxGapMs: 200,
  identityTimeoutMs: 800,
  minHandedness: 0.75,
  identityBasePalmLengths: 0.65,
  identityPalmLengthsPerSecond: 5,
  maxScaleLogJump: 0.35,
  edgeMargin: 0.025,
  minPalmPixels: 32,
  maxPalmScreenFraction: 0.32,
  maxHandScreenFraction: 0.86,
  minPalmWidthRatio: 0.32,
  minIndexReachRatio: 0.18,
  maxTipDepthRatio: 0.65,
  minLuminance: 18,
  maxLuminance: 248,
  minCaptureFps: 14,
  minTrialCoverage: 0.85,
  modelConfidence: 0.6,
  luminanceSampleSize: 24,
});

export const PINCH_REASONS = Object.freeze({
  ok: 'Mano visible.',
  missing: 'Muestra la mano dentro del recuadro.',
  wrong: 'Muestra la mano seleccionada.',
  uncertain: 'No distingo la mano con claridad. Deja solo una mano delante.',
  cropped: 'Centra la mano para que se vea completa.',
  close: 'Aleja un poco la mano.',
  far: 'Acerca un poco la mano.',
  dark: 'Añade luz sobre la mano.',
  bright: 'Evita la luz directa sobre la mano.',
  side: 'Gira un poco la palma hacia la cámara.',
  jump: 'Mantén la mano en el recuadro para recuperar la señal.',
  malformed: 'No se puede medir este fotograma.',
  folded: 'Muestra pulgar e índice, sin cerrar el puño.',
  depth: 'Gira un poco la mano para que se distingan las dos yemas.',
  slow: 'La cámara va demasiado lenta. Prueba con más luz o cierra otras aplicaciones.',
});
